---
title: "03_Beta_diversity_analysis"
author: "Annegreet Veeken"
date: "`r Sys.Date()`"
---

Note: Figures in the manuscript have been post-processed in Adobe Illustratorso this script does not produce figures exactly as they appear in the manuscript
```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

## Load packages
library(tidyverse)
library(geosphere)
library(easystats)
library(rnaturalearth)
library(rnaturalearthdata)
library(lme4)
library(spdep)
library(sf)
library(broom)
library(MuMIn)
library(patchwork)
library(iNEXT.beta3D)
library(terra)
library(ggnewscale)
library(spatialsample)
library(rsample)

set.seed(123)
```

## Preparing data
```{r load-data}
## Load data
dir <- "~/Data/Globnut_offline/_GLOBNUT1.0/"

globnut <- readRDS("outputs/02_GlobNut.rds") %>% 
  ungroup() 
spec_raw <- read.csv(paste0(dir, "GlobNut1.0_species.csv")) 
spec <- spec_raw %>% 
  ungroup() %>% 
  # only vascular plants
  dplyr::filter(vascular_plant == 1) %>% 
  # convert subspecies to species
  mutate(species_new = 
           str_remove(species_new, pattern = " subsp.*| var\\.")) %>%
  group_by(plot_ID, species_new) %>% # aggregate by species
  summarise(cover = sum(cover, na.rm = TRUE)) %>% 
  dplyr::filter(cover != 0)  %>% 
  #  to 100 %
  group_by(plot_ID) %>% 
  mutate(covertot = sum(cover), 
         cover = round(cover/covertot*100))  %>% 
  left_join(globnut %>% dplyr::select(plot_ID, cell), by = "plot_ID") %>% 
  drop_na(cell) %>% 
  filter(cover > 0)


```


## iNEXT
```{r nobs}
# in cell check diff in sample year
# discard plot pairs sampled > 10 year  from each other
plot_ids <- globnut %>% 
  group_by(cell) %>% 
  # all combinations of plots in a cell
  tidyr::expand(plot_x = plot_ID, plot_y = plot_ID) %>% 
  left_join(globnut %>% select(plot_ID, sample_year), by = c("plot_x" = "plot_ID")) %>% 
  left_join(globnut %>% select(plot_ID, sample_year), by = c("plot_y" = "plot_ID"), 
            suffix = c("_x","_y")) %>% 
  # amount of years between sampling
  mutate(diff_year = abs(sample_year_x - sample_year_y)) %>% 
  # discard plot pairs that have been sampled more than 10 years apart
  # select the  oldest plot
  mutate(oldest_plot = ifelse(sample_year_x < sample_year_y, plot_x, plot_y)) %>% 
  filter(!plot_x == plot_y) %>% # same plots
  filter(diff_year > 10) %>% 
  pull(oldest_plot) %>% 
  unique() 

## cells with enough data
nobs <- 3
cell_ids <- globnut %>% 
  # discard plots that are sampled too many years apart
  filter(!plot_ID %in% plot_ids) %>% 
  group_by(cell) %>% 
  summarise(n = n()) %>% 
  filter(n >= nobs) %>% 
  pull(cell)

# Check spatial distribution of cells
world <- ne_countries(scale = "medium", returnclass = "sf")
eurasia <- world[world$continent %in% c("Asia", "Europe"),]
coords_sf <- st_as_sf(unique(globnut[globnut$cell %in% cell_ids, c("cell_lon", "cell_lat")]), 
                      coords = c("cell_lon", "cell_lat"), crs = 4326)
  
p <- ggplot() +
  geom_sf(data = eurasia, fill = "grey90", col = "grey90") +
  geom_sf(data = coords_sf,  alpha = 0.25) +
  coord_sf(crs = "+proj=lcc +lat_1=45 +lat_2=55 +lat_0=50 +lon_0=35",
           xlim = c(-4000000, 4500000), ylim = c(-1000000, 4500000)) +
  theme_bw() 
p

```


```{r running-inext}
## Run iNext for rarefaction and extrapolation of beta diversity
# Convert to incidence format for inext
# incidence_data <- spec %>%
#   filter(!plot_ID %in% plot_ids) %>%
#   filter(cell %in% cell_ids) %>%  # cells with at least nobs observations
#   filter(!cell == 538542) %>% # only 1 vasc species because high moss abundance, which iNext doesn't like
#   ungroup() %>%
#   dplyr::select(cell, plot_ID, species_new, cover) %>%
#   mutate(species_new = str_replace(species_new, pattern = "[:space:]", replacement = "_")) %>%
#   group_split(cell) %>%
#   purrr::map(., ~pivot_wider(.,names_from = "plot_ID",values_from = "cover", values_fill = 0) %>%
#                dplyr::select(.,-cell) %>%
#                column_to_rownames("species_new") %>%
#                as.matrix())
# 
# beta_results <- iNEXTbeta3D(
#   data = incidence_data,
#   diversity = "TD",  # Taxonomic diversity
#   q = c(0, 1, 2),   # Multiple diversity orders
#   datatype = "abundance",
#   base = "coverage",
#   level = 0.9,
#   nboot = 200
# )
# saveRDS(beta_results, "outputs/inext_beta_output.rds")
beta_results <- readRDS("outputs/inext_beta_output.rds")
# Extract beta diversity estimates
beta0 <- beta_results %>% 
  map_df(., "beta") %>% 
  filter(Order.q == 0) %>% 
  mutate(cell = cell_ids[!cell_ids == 538542]) %>% 
  rename(beta_inext = Beta)


```

## Preparing environmental variables
```{r env-var}
## Calculating explanatory variables to the cell level
env_var <- globnut %>% 
 # same plots and cells as the incidence data
 filter(!plot_ID %in% plot_ids) %>% 
 filter(cell %in% cell_ids) %>% 
 group_by(cell) %>% 
 summarise(
   # Distance between plots
   distm = mean(distm(cbind(lon, lat), fun = distGeo)),
           # Elevation difference between plots
           elev = {diff_matrix <- abs(outer(elev, elev, "-"))
           mean(diff_matrix[lower.tri(diff_matrix)])
           },
           # Average climate
           MAT = mean(MAT, na.rm = TRUE),
           MAP = mean(MAP, na.rm = TRUE),
           PET = mean(PET, na.rm = TRUE),
           # n deposition
           ndep = mean(ndep),
           # Average N/P
           mean_np = mean(NP),
           # Differences in NP
           dif_np = {diff_matrix <- abs(outer(NP, NP, "-"))
           mean(diff_matrix[lower.tri(diff_matrix)])
           }
           ) %>% 
 mutate(ndep = log(ndep/5),# to g/ha/yr
        dif_np = log(dif_np),
        mean_np = log(mean_np),
        distm = log(distm +1),
        elev = log(elev+1)
        ) %>% 
 drop_na()


# create data frame with model data
mod_dat <- env_var %>%    
  # cell coordinates
  left_join(globnut %>% 
              dplyr::select(cell, cell_lon, cell_lat) %>% 
              distinct(), by = "cell") %>%
  # standardized beta div
  left_join(beta0 %>% dplyr::select(cell, beta_q0 = beta_inext), by = "cell") %>%
  # scale expl variables 
  mutate(across(c("distm", "elev", "MAT", "MAP", "PET", "ndep", "mean_np", "dif_np"), ~scale(.x)[,1],  .names = "{.col}_scaled")) %>% 
  drop_na() 

# functions to reverse standardization
unstand_ndep <- function(x) {x  * sd(mod_dat$ndep) + mean(mod_dat$ndep)}
unstand_np <- function(x) {x  * sd(mod_dat$mean_np) + mean(mod_dat$mean_np)}
unstand_npdif <- function(x) {x  * sd(mod_dat$dif_np) + mean(mod_dat$dif_np)}

```

## Beta diversity modelling
```{r model}
fm_full <- "distm_scaled + elev_scaled + MAT_scaled + 
                        MAP_scaled + PET_scaled + ndep_scaled  + dif_np_scaled + 
                        mean_np_scaled + I(mean_np_scaled^2) + ndep_scaled*dif_np_scaled + 
            ndep_scaled*mean_np_scaled"
# full model 
full_model_q0 <- lm(formula(paste0("log(beta_q0) ~",fm_full)), 
  data = mod_dat,
  na.action = "na.fail") 

dd <- dredge(full_model_q0,
               subset = ndep_scaled & dif_np_scaled & mean_np_scaled,  # Always include focal variable
  rank = "AICc")
subset(dd, delta <= 2)

selected_model_q0 <- lm(get.models(dd,1)[[1]], data = mod_dat)
# Model checks
check_model(selected_model_q0)
summary(selected_model_q0)
```


## Vizualisation
```{r figures}
# Line plots
ndep_pred_q0 <- ggeffects::ggpredict(selected_model_q0, term = "ndep_scaled[all]") %>% 
  as.data.frame() %>%
  mutate(ndep = unstand_ndep(x) %>% exp) 
difnp_pred_q0 <- ggeffects::ggpredict(selected_model_q0, term = "dif_np_scaled[all]") %>% 
  as.data.frame() %>%
  mutate(dif_np = unstand_npdif(x) %>% exp)
meannp_pred_q0 <- ggeffects::ggpredict(selected_model_q0, term = "mean_np_scaled[all]") %>% 
  as.data.frame() %>%
  mutate(mean_np = unstand_np(x) %>% exp) 

count_limits <- c(0,10)
line_colour <- "#2b8cbe"
ylimits <- c(0,4.5)
ylabel <- "Effective number of species"

p1 <- ggplot(mod_dat, aes(x = exp(unstand_ndep(ndep_scaled)), y = beta_q0)) +
  geom_hex() +
    scale_fill_gradient("Count",low = "grey90", high = "grey40", limits = count_limits) +
   new_scale_fill() + 
    geom_ribbon(data = ndep_pred, aes(x = ndep, y = predicted, ymin = conf.low, 
             ymax = conf.high), alpha = .5, col = NA, fill = line_colour) +
    geom_line(data = ndep_pred, aes(x = ndep, y = predicted), color = line_colour) +
    scale_x_continuous(Average~annual~N~deposition~(kg~ha^-1), 
                       trans = "log",
                       breaks = c(1,2,5,10,25,60),
                       labels = c(1,2,5,10,25,60),
                      limits = c(1,85)) +
  scale_y_continuous(ylabel, limits = ylimits)  +
  theme_bw() 
p1
p2 <-  ggplot(mod_dat, aes(x = exp(dif_np), y = beta_q0)) +
  geom_hex() +
    scale_fill_gradient("Count",low = "grey90", high = "grey40", limits = count_limits) +
   new_scale_fill() + 
    geom_ribbon(data = difnp_pred, aes(x = dif_np, y = predicted, ymin = conf.low, 
             ymax = conf.high), alpha = .5, col = NA, fill = line_colour) +
    geom_line(data = difnp_pred, aes(x = dif_np, y = predicted), color = line_colour) +
    scale_x_continuous("Average difference in N/P") +
  scale_y_continuous(ylabel, limits = ylimits) +
  theme_bw() 


p3 <- ggplot(mod_dat, aes(x = exp(mean_np), y = beta_q0)) +
    geom_hex() +
    scale_fill_gradient("Count",low = "grey90", high = "grey40", limits = count_limits) +
    new_scale_fill() + 
    geom_ribbon(data = meannp_pred, aes(x = mean_np, y = predicted, ymin = conf.low,
             ymax = conf.high), alpha = .5, col = NA, fill = line_colour) +
    geom_line(data = meannp_pred, aes(x = mean_np, y = predicted), color = line_colour) +
    scale_x_continuous("Mean N/P") +
  scale_y_continuous(ylabel, limits = ylimits) +
  theme_bw()

pp <- ((p1|p2|p3) + plot_layout(guides = "collect", axes = "collect")+ plot_annotation(tag_levels = "a")) & theme(legend.position = "bottom")
pp

ggsave("figures/202511-Figures-resubmission/PDFs-for-Ton/fig4.pdf", dpi = 300, width = 7.24, height = 4)
```

## Model outputs for supplementary
```{r tabels}

# function for formatting table
result_table <- function(mod){
  tab <-  mod %>% 
  model_parameters() %>%   
  mutate(Parameter = case_match(Parameter,
                           "(Intercept)" ~ "Intercept",
                "dif_np_scaled" ~ "Difference N/P",
                "ndep_scaled" ~ "N deposition",
                "mean_np_scaled" ~ "Mean N/P",
                "I(mean_np_scaled^2)" ~ "Mean N/P<sup>2</sup>",
                "MAP_scaled" ~ "Mean MAP",
                "distm_scaled" ~ "Geographical distance")) %>% 
  # Combine coefficient and SE
  mutate(`Estimate (SD)`= paste0(round(Coefficient, 3), " (", round(SE, 3), ")"),
      # Combine CI
      CI = paste0("[", round(CI_low, 3), ", ", round(CI_high, 3), "]"),
      `Significance level` = case_when(
        p < 0.001 ~ "***",
                    p < 0.01 ~ "**",
                    p < 0.05 ~ "*",
                    TRUE ~ "NS"),
      `p-value` = case_when(p < 0.001 ~ "<0.001",
                              TRUE ~ as.character(round(p,4)))) %>% 
  select(Parameter, `Estimate (SD)`, CI, `p-value`, `Significance level`) %>% 
  add_row(Parameter = c("Adjusted R<sup>2</sup>"),
          `Estimate (SD)` = c(round(r2(mod)$R2_adjusted,3)) %>% as.character()) %>% 
  replace_na(list(`Estimate (SD)` = "-", CI = "-", `p-value` = "-", `Significance level` = "-")) %>% 
  knitr::kable()
  return(tab)
}
# function for model selection table
model_selection_tab <- function(dd){ 
  dd %>% 
    as.data.frame() %>% 
    slice_head(n = 10) %>% 
    mutate(across(where(is.numeric), ~round(.,digits = 3))) %>% 
    mutate(across(where(is.numeric), ~as.character(.) %>% replace_na( "-"))) %>% 
    rename(Intercept =  `(Intercept)`,
          `Difference N/P` = dif_np_scaled,
          `N deposition` = ndep_scaled,
          `Mean N/P` = mean_np_scaled,
          `Mean N/P<sup>2</sup>` =  `I(mean_np_scaled^2)`,
          `Mean MAP` = MAP_scaled,
          `Geographical distance` = `distm_scaled`,
          `Difference N/P:N deposition` = `dif_np_scaled:ndep_scaled`,
           `Mean N/P:N deposition`= `mean_np_scaled:ndep_scaled`,
          `Mean MAT` = MAT_scaled,
          `Mean PET` = PET_scaled,
          `Elevation difference` = elev_scaled) %>% 
    knitr::kable()
}

# table for supplementary 
result_table(selected_model_q0)
model_selection_tab(dd)
```


# Spatial cross valication
```{r spatial-cross}
globnut_sf <- sf::st_as_sf(mod_dat, coords = c("cell_lon","cell_lat"), crs = 4326)
globnut_sf$residuals <- residuals(selected_model_q0)
globnut_sp <- as(globnut_sf, "Spatial")

# Variogram
emp_variogram <- variogram(
  residuals ~ 1, 
  data = globnut_sp,
  cutoff = 10000,
  width = 10   
)

fit_vario <- fit.variogram(emp_variogram, vgm("Exp"), fit.method = 6)
plot(emp_variogram, fit_vario,
     xlab = "Distance (m)",
     ylab = "Semivariance")


# function to calculate rmse 
evaluate_fit <- function(mod, id, split, nclus) {
  mod <- lm(formula(mod),
              data = analysis(split)
  )
  
  test_data <- assessment(split)
  pred <- predict(mod, newdata = test_data, allow.new.levels = TRUE)
  res <- tibble(rmse = sqrt(mean((log(test_data$beta_q0) - pred)^2, na.rm = TRUE)),
                mae = mean(abs(log(test_data$beta_q0) - pred), na.rm = TRUE),
                rsq = cor(log(test_data$beta_q0), pred, use = "complete.obs")^2,
                clus = nclus,
                id = id,
                mod = list(mod))
  }

# chose number of folds = 20 
nfolds <- 20
folds <- spatial_clustering_cv(globnut_sf, v = nfolds)
cv <- map2_dfr(folds$id, folds$splits, ~evaluate_fit(selected_model_q0,.x,.y, nfolds))

x <- autoplot(folds)$data %>% 
  as.data.frame() %>% 
  rename(id = .fold.) %>% 
  left_join(.,cv, by = c("id"))
# Euroasia shape file
world <- ne_countries(scale = "medium", returnclass = "sf")
eurasia <- world[world$continent %in% c("Asia", "Europe"),]

ggplot() +
  geom_sf(data = eurasia) +
  geom_sf(data = x, aes(geometry = geometry, color = rmse), alpha = 0.5) +
  labs(color = "RMSE") +
  coord_sf(xlim = c(-10, 150), ylim = c(35, 70)) +
  scale_color_viridis_c() +
  theme_bw() +
  theme(legend.position = "bottom")
ggsave("figures/202511-Figures-resubmission/Supp-Spatial_cross_validation_beta.png", dpi = 300)
```

