---
title: "Linear mixed models"
author: "Annegreet Veeken"
date: "`r Sys.Date()`"
output:
  word_document: default
params: 
  data: "outputs/02_GlobNut_subsampled.rds"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, fig.height=4, fig.width=4, message=FALSE, warning=FALSE)

## Load packages
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(vegan)) install.packages("vegan")
if(!require(performance)) install.packages("performance")
if(!require(parameters)) install.packages("parameters")
if(!require(ggeffects)) install.packages("ggeffects")
if(!require(lme4)) install.packages("lme4")
if(!require(knitr)) install.packages("knitr")
if(!require(insight)) install.packages("insight")
if(!require(partR2)) install.packages("partr2")

## Load data
globnut <- readRDS(params$data) %>% ungroup() %>% 
  mutate(soil_age = factor(soil_age, levels = c("1", "2", "3")),
         lith_simp = factor(lith_simp, levels = c("acid", "intermediate",
                                                  "calcareous","mafic")))  %>%
  filter(!lith_simp == "mafic") %>% 
  drop_na()

n_boot <- 10

# formula for predictors
pred <- "MAT + I(MAT^2) + MAP + I(MAP^2) + ndep + soil_age + lith_simp + (1|cell)"
# batches for partioning of r2
batch <- list(climate = c("MAT", "MAP", "I(MAT^2)","I(MAP^2)"),
               geo = c("soil_age", "lith_simp"),
               anthro = "ndep")
```
## Nutrients and environment (Linear mixed model) 
### N
formula: `r paste("log(N) ~", pred)`

```{r fig.height=7, fig.width=7}
# # nested random effect
# re_nested_N <- lmer(N ~ 1 + (plot_ID|cell),
#                      data = globnut)
# # ranef(re_model_N) # very small - no need to fit nested effect?
# 
# re_N <- lmer(N ~ 1 + (1|cell),
#                      data = globnut)
# ranef(re_N) 

full_model_N <- lmer(formula(paste("log(N) ~", pred)),
                     data = globnut)

check_model(full_model_N)

check_heteroscedasticity(full_model_N)
check_outliers(full_model_N)
```

```{r}
ggpredict(full_model_N, terms = "MAT [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_N, terms = "MAP [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_N, terms = "ndep [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_N, terms = "soil_age [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_N, terms = "lith_simp") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)

model_parameters(full_model_N) %>% 
  mutate(across(where(is.numeric), ~round(., digits = 4))) %>% 
  mutate(Parameter = str_remove(Parameter, "lith_simp")) %>% 
  as_tibble() %>% 
  dplyr::select(-t,-df_error,-Group) %>% 
  kable()
r2_n <- r2(full_model_N)
kable(r2_n)
```

```{r, fig.width=6,fig.height=6}

res <- partR2(full_model_N, 
              R2_type = "marginal",
              nboot = n_boot, # set t0 1000 for final analysis
              partbatch = batch,
              allow_neg_r2 = TRUE)

part_r2_n <- res$R2 %>% 
  filter(term %in% c("geo","anthro","climate")) %>% 
  dplyr::select(term, estimate, CI_lower, CI_upper) %>% 
  add_row(term = c("random", "unexplained"),
          estimate = c(r2_n$R2_conditional- r2_n$R2_marginal,
                   1 - r2_n$R2_conditional)) %>% 
  filter(!term == "unexplained") %>% 
  mutate(ymax = cumsum(estimate),
         ymin = lag(ymax, default = 0)) 
part_r2_n %>% 
  ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=term)) +
  geom_rect(col = "black") +
  coord_polar(theta="y") +
  geom_text(x = 2, y = 2, label = paste("N\n","Conditional R2 =",
                                        round(r2_n$R2_conditional, 
                                              digits = 2))) +
  scale_fill_brewer(palette=4) +
  xlim(c(2, 4)) +
  theme_void() 

```

### P
formula:`r paste("log(P) ~", pred)`

```{r fig.height=8, fig.width=7}
full_model_P <- lmer(formula(paste("log(P) ~", pred)), data = globnut)
check_model(full_model_P)

check_heteroscedasticity(full_model_P)
check_outliers(full_model_P)
```

```{r}
ggpredict(full_model_P, terms = "MAT [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_P, terms = "MAP [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_P, terms = "ndep [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_P, terms = "soil_age [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_P, terms = "lith_simp [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)

model_parameters(full_model_P) %>% 
  mutate(across(where(is.numeric), ~round(., digits = 4))) %>% 
  mutate(Parameter = str_remove(Parameter, "lith_simp")) %>% 
  as_tibble() %>% 
  dplyr::select(-t,-df_error,-Group) %>% 
  kable()
r2_p <- r2(full_model_P)
kable(r2_p)
```

```{r fig.width=6,fig.height=6}
res <- partR2(full_model_P, 
              R2_type = "marginal",
              nboot = n_boot, # set t0 1000 for final analysis
              partbatch = batch,
              allow_neg_r2 = TRUE)

part_r2_p <- res$R2 %>% 
  filter(term %in% c("geo","anthro","climate")) %>% 
  dplyr::select(term, estimate, CI_lower, CI_upper) %>% 
  add_row(term = c("random", "unexplained"),
          estimate = c(r2_p$R2_conditional- r2_p$R2_marginal,
                   1 - r2_p$R2_conditional)) %>% 
  filter(!term == "unexplained") %>% 
  mutate(ymax = cumsum(estimate),
         ymin = lag(ymax, default = 0)) 
part_r2_p %>% 
  ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=term)) +
  geom_rect(col = "black") +
  coord_polar(theta="y") +
  geom_text(x = 2, y = 2, label = paste("P\n","Conditional R2 =",
                                        round(r2_p$R2_conditional, 
                                              digits = 2))) +
  scale_fill_brewer(palette=4) +
  xlim(c(2, 4)) +
  theme_void() 

```

### NP
formula:`r paste("log(NP) ~", pred)`

```{r  fig.height=8, fig.width=7}
full_model_NP <- lmer(formula(paste("log(NP) ~", pred)), data = globnut)
check_model(full_model_NP)
# summary(full_model_NP)
check_heteroscedasticity(full_model_NP)
check_outliers(full_model_NP)
```

```{r}
ggpredict(full_model_NP, terms = "MAT [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_NP, terms = "MAP [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE) 
ggpredict(full_model_NP, terms = "ndep [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_NP, terms = "soil_age [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)
ggpredict(full_model_NP, terms = "lith_simp [all]") %>% 
  plot(., show_residuals =  TRUE, show_residuals_line = TRUE)

model_parameters(full_model_NP) %>% 
  mutate(across(where(is.numeric), ~round(., digits = 4))) %>% 
  mutate(Parameter = str_remove(Parameter, "lith_simp")) %>% 
  as_tibble() %>% 
  dplyr::select(-t,-df_error,-Group) %>% 
  kable()
r2_np <- r2(full_model_NP)
kable(r2_np)
```

```{r fig.width=6,fig.height=6}
res <- partR2(full_model_NP, 
              R2_type = "marginal",
              nboot = n_boot, # set t0 1000 for final analysis
              partbatch = batch,
              allow_neg_r2 = TRUE)

part_r2_np <- res$R2 %>% 
  filter(term %in% c("geo","anthro","climate")) %>% 
  dplyr::select(term, estimate, CI_lower, CI_upper) %>% 
  add_row(term = c("random", "unexplained"),
          estimate = c(r2_np$R2_conditional- r2_np$R2_marginal,
                   1 - r2_np$R2_conditional)) %>% 
  filter(!term == "unexplained") %>% 
  mutate(ymax = cumsum(estimate),
         ymin = lag(ymax, default = 0)) 
part_r2_np %>% 
  ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=term)) +
  geom_rect(col = "black") +
  coord_polar(theta="y") +
  geom_text(x = 2, y = 2, label = paste("N:P\n","Conditional R2 =",
                                        round(r2_np$R2_conditional, 
                                              digits = 2))) +
  scale_fill_brewer(palette=4) +
  xlim(c(2, 4)) +
  theme_void() 
```

```{r}
nutr <- bind_rows(list(N = part_r2_n,
                  P = part_r2_p,
                  NP = part_r2_np), .id = "nutrient")
nutr %>% 
  filter(term %in% c("geo","anthro","climate")) %>%
  mutate(nutrient = factor(nutrient, levels = c("N","P","NP"))) %>% 
  ggplot(aes(x = nutrient, y = estimate, fill = term)) + 
    geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper), 
                  linewidth = 0.5, width = 0.1,
                  position = position_dodge(0.5)) +
    geom_point(shape = 21, size = 2, position = position_dodge(0.5)) +
  geom_hline(yintercept = 0, linetype= "dotted") +
  scale_y_continuous("Semi-partial R2") +
  scale_x_discrete("") + 
  theme_bw()
```

