---
title: "03_zi_beta_regression"
author: "Annegreet Veeken"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
# References:
# - Borcard (2018). Numerical Ecology in R

## Load packages
if (!require(tidyverse)) install.packages("tidyverse")
if (!require(knitr)) install.packages("knitr")
if (!require(vegan)) install.packages("vegan")
if (!require(geosphere)) install.packages("geosphere")
if (!require(terra)) install.packages("terra")
if (!require(raster)) install.packages("raster")
if (!require(easystats)) install.packages("easystats")
if (!require(sf)) install.packages("sf")
if (!require(rnaturalearth)) install.packages("rnaturalearth")
if (!require(rnaturalearthdata))  install.packages("rnaturalearthdata")
if (!require(patchwork)) install.packages("patchwork")
if (!require(ggalt)) install.packages("ggalt")
if (!require(brms)) install.packages("brms")
if (!require(broom)) install.packages("broom")
if (!require(tidybayes)) install.packages("tidybayes")
if (!require(modelr)) install.packages("modelr")
if (!require(vcd)) install.packages("vcd")
```

```{r load data}
## Load data ----
dir <- "Z:/_GLOBNUT1.0/"
globnut <- readRDS("outputs/02_GlobNut.rds") %>% 
  ungroup() %>% 
  filter(!lim == "No limitation by N, P, K") %>% 
  dplyr::filter(between(lat, 35, 75)) %>% 
  dplyr::filter(between(lon, -25, 150)) %>% 
  drop_na %>% 
  mutate(ndep = log(ndep*10), # to g/ha en log
         MAP = log(MAP),
         NP = log(NP),
         biomass = log(biomass)) %>%
  dplyr::select(plot_ID, lon,lat, sample_year, ndep, MAP, MAT, PET, NP, biomass, elev) %>% 
  drop_na() 

# Use EMEP raster for aggregating plots
masras <- raster("Z:/geo_data/EMEP/Data_EMEP_report2023/EMEP01_rv5.0_year.2022met_2021emis.nc")
masras <- extend(masras, extent(-25,150,35,75))
values(masras) <- 1:ncell(masras)

# Get the corresponding grid cells for each plot
globnut$cell <- terra::extract(x = masras, y = as.matrix(globnut[,c("lon","lat")]))
globnut$cell_lon <- xFromCell(masras, globnut$cell) 
globnut$cell_lat <- yFromCell(masras, globnut$cell) 

# species data
spec_raw <- read.csv(paste0(dir, "GlobNut1.0_species.csv"))
```

## Ecoregions

Criteria for selection of regions:

-   at least 10 cells within ecoregion

-   at least 5 plots per cell

```{r ecoregions}
## Extract ecoregions for globnut
# ecoregions <- terra::vect("C:/Users/3768651/OneDrive - Universiteit Utrecht/Documents/Projects/Ongoing/ESy/data/Ecoregions2017/Ecoregions2017.shp")
# ecoregions <- terra::rasterize(ecoregions, masras, "ECO_NAME")
# # crs(ecoregions)
# coords <- globnut %>% 
#   select(cell, cell_lon, cell_lat) %>% 
#   distinct()
# 
# ecoreg_globnut <- cbind(cell = coords[,c("cell")], 
#                         terra::extract(ecoregions, coords[,c("cell_lon", "cell_lat")]))
# 
# saveRDS(ecoreg_globnut, "outputs/Ecoregions_emep_grid.rds")
ecoreg_globnut <- readRDS("outputs/Ecoregions_emep_grid.rds")

# add to globnut
globnut <- globnut %>% 
  left_join(ecoreg_globnut, by = "cell") %>% 
  rename(region = ECO_NAME) 

# check amount of cells with enough plots per region
plotcounts  <- globnut %>% 
  group_by(region, cell, cell_lon, cell_lat) %>% 
  summarise(count = n()) %>% 
  filter(count >= 5)
```

```{r plot selection}
## Select plots for analysis ----
set.seed(1234)
# randomly select 5 samples per cell
plot_ids <- globnut %>%
  group_by(cell) %>% 
  mutate(n = n()) %>% 
  filter(n >= 5) %>% 
  sample_n(size = 5) %>% 
  dplyr::select(region, cell, plot_ID) %>% 
  filter(!is.na(region)) %>% 
  distinct()

cellcounts  <- globnut %>% 
  filter(plot_ID %in% plot_ids$plot_ID) %>% 
  group_by(region) %>% 
    summarise(count = n_distinct(cell)) %>% 
  arrange(desc(count))

region_alias <- data.frame(region = c("Alps conifer and mixed forests",
                                      "Central European mixed forests",
                                      "East Siberian taiga","European Atlantic mixed forests",
                                      "Kazakh steppe","Pannonian mixed forests",
                                      "Western European broadleaf forests"),
                           alias = c("alps", "north_eu", "jak", "west_eu", "kaz", 
                                     "east_eu", "central_eu"),
                           label = c("Alps", "Northeastern Europe", "Yakutsk", "Western Europe",
                                     "Kazakhstan", "Eastern Europe", "Central Europe"))
region_color <- c("Alps conifer and mixed forests" = '#f781bf',
                  "Central European mixed forests" = '#377eb8',
                  "East Siberian taiga" = '#a65628',
                  "European Atlantic mixed forests" = '#984ea3',
                  "Kazakh steppe" = '#4daf4a',
                  "Pannonian mixed forests" = '#e41a1c',
                  "Western European broadleaf forests" = '#ff7f00')
region_label <- region_alias$label
names(region_label) <- region_alias$region

cellcounts %>% 
  left_join(region_alias, by = "region") %>% 
  slice_head(n = 10) %>% 
  kable()

# regions with at least 10 cells
reg <- cellcounts %>% 
  filter(count >= 10) %>% 
  pull(region)

sf::sf_use_s2(FALSE)
europe <- ne_countries(scale = "medium", 
                       # country = country,
                       returnclass = "sf") %>% 
  # fix geometry of russia (sf_use_s2() must be FALSE for this)
  st_make_valid() %>% 
  st_crop(., c(xmin = -25, ymin = 35, xmax = 150, ymax = 72)) 

ggplot() +
  geom_sf(data = europe, fill = NA, col = "black")  +
  geom_point(data = plotcounts[plotcounts$region %in% reg, ],
             aes(x = cell_lon, y = cell_lat, color = region), size = 1, 
             alpha = 0.5) +
  geom_encircle(data = plotcounts[plotcounts$region %in% reg, ], 
                aes(x = cell_lon, y = cell_lat, group = region, color = region),
                expand = 0) +
  geom_point(data = plotcounts[!plotcounts$region %in% reg,],
             aes(x = cell_lon, y = cell_lat), size = 1, 
             color = "grey",alpha = 0.5) +
  scale_x_continuous("Longitude") +
  scale_y_continuous("Latitude") +
  scale_color_manual(values = region_color, labels = region_label) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.title = element_blank())
ggsave("figures/Regions-beta-div.png", height = 5, width = 7)
```

```{r prepare data}
## Prepare data ----
spec <- spec_raw %>% 
  ungroup() %>% 
  # only vascular plants
  dplyr::filter(vascular_plant == 1) %>% 
  # convert subspecies to species
  mutate(species_new = 
           str_remove(species_new, pattern = " subsp.*| var\\.")) %>%
  group_by(plot_ID, species_new) %>% # aggregate by species
  summarise(cover = sum(cover, na.rm = TRUE)) %>% 
  dplyr::filter(cover != 0)  %>% 
  #  to 100 %
  group_by(plot_ID) %>% 
  mutate(covertot = sum(cover), 
         cover = round(cover/covertot*100)) %>% 
  # Average abundance per cell
  left_join(globnut[,c("cell", "plot_ID")], by = "plot_ID") %>% 
  filter(plot_ID %in% plot_ids$plot_ID) %>%  # select for sampled plots
  group_by(cell, species_new) %>% 
  summarise(cover = mean(cover)) 

spec_wide <- spec  %>% 
   dplyr::select(cell, species_new, cover) %>% 
  # convert to wide to calculate diversity measures
  pivot_wider(names_from = species_new, 
              values_from = cover, values_fill = 0) 

# Prepare environmental data
env_data <- globnut %>% 
  # filter for selected plots
  filter(plot_ID %in% plot_ids$plot_ID) %>% 
  # get average per cell
  group_by(cell) %>% 
  summarise(across(all_of(c("MAT","MAP","PET","NP",
                            "biomass","ndep","elev")), mean)) %>% 
  left_join(plotcounts, by = "cell")
```

```{r dissimilarity}
## Dissimilarity calculations
# calculate bray curtis dissimilarity 
cell_names <- plot_ids %>% 
  ungroup %>% 
  dplyr::select(-plot_ID) %>% 
  distinct() %>% 
  mutate(member = 1:nrow(.))

diss_spec <-   
  # calculate dissimilarity as Bray-curtis (aka percentage difference)
  vegdist(decostand(spec_wide[,-1], method = "hellinger"), method = "bray") %>% 
  # convert to dataframe, to long format and add plot pair to facilitate merge with environmental dat
  as.matrix(.) %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(cols = !member1, names_to = "member2", values_to = "beta") %>% 
  mutate(member2 = as.numeric(member2)) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1)  %>% 
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) 

# Calculate geographical distance plot pairs
coordinates <- env_data[,c("cell_lon","cell_lat")]
dist_geo <- distm(coordinates, fun = distGeo) %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "distance") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2"))  %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2) %>% 
  mutate(distance = scale(distance))

# Calculate dissimilarity (euclidean) in environmental variables for plot pairs 
NP_diss <- dist(scale(env_data$NP)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_NP") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)
ndep_diss <- dist(scale(env_data$ndep)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_ndep") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)
MAT_diss <- dist(scale(env_data$MAT)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_MAT") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)
MAP_diss <- dist(scale(env_data$MAP)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_MAP") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)
PET_diss <- dist(scale(env_data$PET)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_PET") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)

biomass_diss <- dist(scale(env_data$biomass)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_biomass") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)
elev_diss <- dist(scale(env_data$elev)) %>%  
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "diss_elev") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric()) %>% 
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)


# calculate mean between pairs for NP and ndep
NP_mean <- outer(env_data$NP, env_data$NP, FUN = "+") %>% # add plot pairs
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "mean_np") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric(),
         mean_np = mean_np/2) %>% # get mean
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)

ndep_mean <- outer(env_data$ndep, env_data$ndep, FUN = "+") %>% # add plot pairs
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", values_to = "mean_ndep") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>% as.numeric(),
         mean_ndep = mean_ndep/2) %>% # get mean
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)

biomass_mean <- outer(env_data$biomass, env_data$biomass, FUN = "+") %>% # add plot pairs
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(member1 = 1:nrow(.)) %>% 
  pivot_longer(-member1, names_to = "member2", 
               values_to = "mean_biomass") %>% 
  mutate(member2 = str_remove(member2, pattern = "V") %>%
           as.numeric(),
         mean_biomass = mean_biomass/2) %>% # get mean
  # filter plots that compare to themselves
  filter(!member1 == member2) %>% 
  # filter doubles e.g. pairs 1-2 and 2-1
  filter(member2 > member1) %>% 
  # add plot ids
  left_join(cell_names, by = c("member1" = "member")) %>% 
  left_join(cell_names, by = c("member2" = "member"), suffix = c("1","2")) %>% 
  filter(region1 == region2) %>% 
  dplyr::select(-region1,-region2)
```

# Chi-square
```{r chisquare}
reg_data <- diss_spec %>% 
  # join with predictors
  left_join(NP_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(ndep_mean, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(NP_mean, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(biomass_mean, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(dist_geo, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(MAT_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(MAP_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(PET_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(ndep_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(biomass_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  left_join(elev_diss, by = c("member1", "member2", "cell1","cell2")) %>% 
  dplyr::select(member1, member2, cell1, cell2, region = region1,  everything()) %>%   dplyr::select(-region2) %>% 
    # filter for regions with enough data
  right_join(region_alias, by = "region") 

# count table plots with total dissimilarity per region
count_one <- reg_data %>%
  mutate(is_one = ifelse(beta == 1, "One", "Not one"))
table(count_one$alias, count_one$is_one)
x2 <- chisq.test(table(count_one$is_one, count_one$alias))
x2

mosaic(~alias + is_one, data = count_one,  shade = TRUE, rot_labels = c(0,90,0,0),
       just_labels = "right", varnames = FALSE)

```

# model 1
Zero-inflation modeled as region + all geographical/environmental distance
```{r}
m_logit_full <- brm(bf(1 - beta ~ # 1 minus beta to allow zero-inflated model
                  distance + 
               mean_ndep +
               mean_np +
               mean_biomass +
               diss_ndep +
               diss_NP  + 
               diss_MAT + 
               diss_MAP + 
               diss_PET + 
               diss_biomass +
              diss_elev +
              region,
              zi ~ region + distance + 
               diss_ndep +
               diss_NP  + 
               diss_MAT + 
               diss_MAP + 
               diss_PET + 
               diss_biomass +
              diss_elev),
             data = reg_data,
  family = zero_inflated_beta(link = "logit"),
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  file = "outputs/brms_model_logit.rds",
  file_refit = "on_change")

summary(m_logit_full)
# convergence checks
bayesplot::mcmc_trace(m_logit_full) %>% 
  ggsave("figures/model_checks/full_model_zi_full.pdf", .,
                                      height = 11.7, width = 8.3)
# residual check
reg_data %>%
  add_predicted_draws(m_logit_full) %>%
        summarise(p_residual = mean(.prediction < 1 - beta),
                  z_residual = qnorm(p_residual),
                  .groups = "drop_last") %>%
        ggplot(aes(sample = z_residual)) +
        geom_qq() +
        geom_abline()
pp_check(m_logit_full, ndraws =  50)

```

```{r visualization}
y_lim <- c(0.6,1)
p1 <- reg_data %>%
  group_by(region) %>% 
  data_grid(diss_NP = mean(diss_NP),
            mean_ndep = seq_range(mean_ndep, n = 20),
            mean_np = mean(mean_np),
            mean_biomass = mean(mean_biomass),
            distance = mean(distance),
            diss_MAT = mean(diss_MAT),
            diss_MAP = mean(diss_MAP),
            diss_PET = mean(diss_PET),
            diss_ndep = mean(diss_ndep),
            diss_biomass = mean(diss_biomass),
            diss_elev = mean(diss_elev)) %>%  
              add_epred_rvars(m_logit_full,
            allow_new_levels = T) %>% 
  mutate(region = factor(region, levels = c("European Atlantic mixed forests",
                                            "Alps conifer and mixed forests",
                                            "Western European broadleaf forests",
                                            "Pannonian mixed forests",
                                            "Central European mixed forests",
                                            "Kazakh steppe",
                                            "East Siberian taiga"
                                            ))) %>% 
  ggplot(aes(x = (exp(mean_ndep)/1000)/5), col = region) +
  stat_lineribbon(aes(ydist = 1 - .epred, col = region, fill = region), .width = 0.95,
                  alpha = 0.5, linetype = "dashed", linewidth = 0.75) + #back transform to dissimilarity
  scale_x_continuous("Average annual N-deposition (kg/ha)", trans = "log",
                     breaks = c(1,2,5,10,20,60),
                     labels = c(1,2,5,10,20,60)) +
  scale_y_continuous("Community dissimilarity", limits = y_lim) +
  scale_fill_manual("",values = region_color, labels = region_label) +
  scale_color_manual("",values = region_color, labels = region_label) +
  theme_bw() 
p1
p2 <- reg_data %>%
  group_by(region) %>% 
  data_grid(diss_NP = mean(diss_NP),
            mean_ndep = mean(mean_ndep),
            mean_np = seq_range(mean_np, n = 20),
            mean_biomass = mean(mean_biomass),
            distance = mean(distance),
            diss_MAT = mean(diss_MAT),
            diss_MAP = mean(diss_MAP),
            diss_PET = mean(diss_PET),
            diss_ndep = mean(diss_ndep),
            diss_biomass = mean(diss_biomass),
            diss_elev = mean(diss_elev)) %>%
  add_epred_rvars(m_logit_full, allow_new_levels = T) %>% 
   mutate(region = factor(region, levels = c("European Atlantic mixed forests",
                                            "Alps conifer and mixed forests",
                                            "Western European broadleaf forests",
                                            "Pannonian mixed forests",
                                            "Central European mixed forests",
                                            "Kazakh steppe",
                                            "East Siberian taiga"
                                            ))) %>% 
  ggplot(aes(x = exp(mean_np), col = region)) +
  stat_lineribbon(aes(ydist = 1 - .epred, col = region, fill = region), .width = 0.95,  
                  alpha = 0.5, linetype = "dashed", linewidth = 0.75) + #back transform to dissimilarity
  scale_x_continuous("N/P") +
  scale_y_continuous("Community dissimilarity", limits = y_lim) +
  scale_fill_manual("",values = region_color, labels = region_label) +
  scale_color_manual("",values = region_color, labels = region_label) +
  theme_bw()
p2
p3 <- reg_data %>%
  group_by(region) %>% 
  data_grid(diss_NP = mean(diss_NP),
            mean_ndep = mean(mean_ndep),
            mean_np = mean(mean_np),
            mean_biomass = seq_range(mean_biomass, n = 20),
            distance = mean(distance),
            diss_MAT = mean(diss_MAT),
            diss_MAP = mean(diss_MAP),
            diss_PET = mean(diss_PET),
            diss_ndep = mean(diss_ndep),
            diss_biomass = mean(diss_biomass),
            diss_elev = mean(diss_elev)) %>%
  add_epred_rvars(m_logit_full, allow_new_levels = T) %>% 
   mutate(region = factor(region, levels = c("European Atlantic mixed forests",
                                            "Alps conifer and mixed forests",
                                            "Western European broadleaf forests",
                                            "Pannonian mixed forests",
                                            "Central European mixed forests",
                                            "Kazakh steppe",
                                            "East Siberian taiga"
                                            ))) %>% 
  ggplot(aes(x = exp(mean_biomass), col = region)) +
  stat_lineribbon(aes(ydist = 1 - .epred, col = region, fill = region),  .width = 0.95,
                  alpha = 0.5,linetype = "dashed",linewidth = 0.75) + #back transform to dissimilarity
  scale_x_continuous("Biomass (g/m2)") +
  scale_y_continuous("Community dissimilarity", limits = y_lim) +
  scale_fill_manual("",values = region_color, labels = region_label) +
  scale_color_manual("",values = region_color, labels = region_label) +
  theme_bw() 
p3
```

```{r model_output}
all_param <- model_parameters(m_logit_full)
all_param <- all_param %>% 
  mutate(across(where(is.numeric), ~round(., digits = 4))) %>% 
  # swap the signs because of 1-beta
  mutate(across(c(Median,CI_low,CI_high), ~.*-1)) %>% 
  # filter(!Parameter %in% c("b_Intercept", "phi") %>% 
  mutate(ok = case_when(str_detect(Parameter, "region") ~ "Region",
                        str_detect(Parameter, "dis" ) ~ "Dissimilarity",
                        str_detect(Parameter, "mean") ~ "Mean"),
    Parameter = case_match(Parameter,
                           "b_Intercept" ~ "Intercept",
                           "b_zi_Intercept" ~ "Intercept",
                           "phi" ~ "Phi",
                "b_diss_NP" ~ "Distance N/P",
                "b_mean_ndep" ~ "Mean N-deposition",
                "b_mean_np" ~ "Mean N/P",
                "b_mean_biomass" ~ "Mean biomass",
                "b_distance" ~ "Geographical distance",
                "b_diss_elev" ~ "Elevation",
                "b_diss_MAT" ~  "Distance MAP",
                "b_diss_MAP" ~ "Distance MAT",
                "b_diss_PET" ~ "Distance PET",
                "b_diss_ndep" ~ "Distance N-deposition",
                "b_diss_biomass" ~ "Distance biomass",
                "b_regionCentralEuropeanmixedforests" ~ "Northeastern Europe",
                "b_regionEastSiberiantaiga" ~ "Yakutsk",
                "b_regionEuropeanAtlanticmixedforests" ~ "Western Europe",
                "b_regionKazakhsteppe" ~ "Kazakhstan",
                "b_regionPannonianmixedforests" ~ "Eastern Europe",
                "b_regionWesternEuropeanbroadleafforests" ~ "Central Europe",
                "b_zi_diss_NP" ~ "Distance N/P",
                # "b_zi_mean_ndep" ~ "Mean N-deposition",
                # "b_zi_mean_np" ~ "Mean N:P",
                # "b_zi_mean_biomass" ~ "Mean biomass",
                "b_zi_distance" ~ "Geographical distance",
                "b_zi_diss_elev"~"Elevation", 
                "b_zi_diss_MAT" ~ "Distance MAP",
                "b_zi_diss_MAP" ~ "Distance MAT",
                "b_zi_diss_PET" ~ "Distance PET",
                "b_zi_diss_ndep" ~ "Distance N-deposition",
                "b_zi_diss_biomass" ~ "Distance biomass",
                "b_zi_regionCentralEuropeanmixedforests" ~ "Northeastern Europe",
                "b_zi_regionEastSiberiantaiga" ~ "Yakutsk",
                "b_zi_regionEuropeanAtlanticmixedforests" ~ "Western Europe",
                "b_zi_regionKazakhsteppe" ~ "Kazakhstan",
                "b_zi_regionPannonianmixedforests" ~ "Eastern Europe",
                "b_zi_regionWesternEuropeanbroadleafforests" ~ "Central Europe")) 
kable(all_param)

p4 <- all_param %>% 
  filter(Component == "conditional") %>% 
  # filter(!Parameter == "Intercept") %>% 
  filter(ok == "Dissimilarity") %>% 
  mutate(Parameter = factor(Parameter, levels = c("Geographical distance", "Elevation",
                                                  "Distance MAT", "Distance MAP", "Distance PET",
                                                  "Distance N-deposition","Distance N/P", 
                                                  "Distance biomass"))) %>% 
  ggplot(aes(y = Parameter, x = Median)) +
   geom_point() +
  geom_errorbar(aes(xmin = CI_low, xmax = CI_high)) +
  geom_vline(aes(xintercept = 0)) +
  scale_x_continuous("Effect on community dissimilarity") +
  scale_y_discrete("") + 
  theme_bw()
p_all <- p1 + free(p2) + p3 + p4 +
  plot_layout(guides = 'collect') +  plot_annotation(tag_levels = 'a') &
  theme(legend.position = "bottom", text = element_text(size = 10))

ggsave("figures/Files_Ton/fig4_beta_div.pdf", p_all, dpi = 300, width = 7, height = 7)
ggsave("figures/fig4_beta_div.png", p_all, dpi = 300, width = 7, height = 7)
```

```{r}
var_labels2 <- c(MAT = "MAT (°C)",
                 PET = "PET (mm/yr)",
                 MAP = "MAP (mm/yr)",
                 elev = "Elevation (m.a.s.l)",
                 biomass = "Biomass (g/m2)",
                 ndep = "N-deposition (kg/ha/yr)",
                 NP = "N/P" )
# environmental variable - boxplot by region
g <- env_data %>% 
  filter(region %in% region_alias$region) %>% 
  dplyr::select(-cell_lat,-cell_lon,-count) %>% 
  mutate(across(c("MAP" , "NP","biomass","ndep"), ~exp(.))) %>%
  mutate(ndep = ndep/1000/5) %>% 
  pivot_longer(cols = MAT:elev, names_to = "var", values_to = "value") %>% 
  mutate(var = factor(var, levels = c("MAT","MAP","PET", "ndep", "NP", "biomass", "elev"))) %>% 
  mutate(region = factor(region, levels = c("European Atlantic mixed forests",
                                            "Alps conifer and mixed forests",
                                            "Western European broadleaf forests",
                                            "Pannonian mixed forests",
                                            "Central European mixed forests",
                                            "Kazakh steppe",
                                            "East Siberian taiga"
                                            ))) %>% 
  ggplot(aes(x = region, y = value, fill = region)) +
  geom_boxplot() +
  facet_wrap(~var, scales = "free_y", labeller = as_labeller(var_labels2), ncol = 2) +
  scale_fill_manual(values = region_color, labels = region_label) +
  scale_x_discrete("", labels = region_label) +
  scale_y_continuous("") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        legend.position = "none")
ggsave("figures/Sup_env_var_region.png", g, width = 7, height = 7)
ggsave("figures/Files_Ton/Sup_env_var_region.pdf", g, width = 7, height = 7)

```

